# Use starship.def.toml to edit the starship configuration.  There should be an entr daemon
# running which, upon changes to the file, will replace each instance of ${ACCENT_COLOR} with
# the appropriate environment variable.  This hack was cobbled together because starship currently
# does not allow environment variables to be used as a style (which is dumb)

# Inserts a blank line between shell prompts
add_newline = false

format = '''
[┌──\([$username@$hostname](bold ${ACCENT_COLOR})\)-\[$directory\](-\[$git_branch$git_metrics$git_status\])(-\[$nix_shell\])](${ACCENT_COLOR}) $cmd_duration
[└$shell ](${ACCENT_COLOR})'''
# format = '''
# [\[$directory\](-\[$git_branch$git_metrics$git_status\])(-\[$nix_shell\])](${ACCENT_COLOR})[λ ](${ACCENT_COLOR} bold)
# '''
right_format = '$status'

[line_break]
disabled = false

[username]
style_user = 'bold ${ACCENT_COLOR}'
style_root = 'bold red'
format = '[$user]($style)'
disabled = false
show_always = true

[nix_shell]
symbol = '❄️'
format = '[$symbol$name](bold purple)'

[hostname]
ssh_only = false
format = '[$ssh_symbol](bold blue)$hostname'
trim_at = '.companyname.com'
disabled = false

[git_branch]
style = 'bold green'
symbol = ''
format = '[$symbol$branch(hello$banch)](bold green)'

[git_status]
modified = '[✘](bold red)'
up_to_date = 'up'
format = '$up_to_date$modified$up_to_date'

[directory]
truncation_length = 3
truncation_symbol = '…/'
truncate_to_repo = true
style = 'bold white'
format = '[$path]($style)[$read_only]($read_only_style)'

[character]
success_symbol = '[λ](bold ${ACCENT_COLOR})'
error_symbol = '[λ](bold red)'
# success_symbol = '[❯](bold ${ACCENT_COLOR})'
# error_symbol = '[❯](bold red)'

[cmd_duration]
min_time = 1_000
style = "bold dimmed yellow"
format = '◷[$duration]($style) '

[shell]
fish_indicator =       '─[󰈺](bold ${ACCENT_COLOR})'
powershell_indicator = '[_](bold ${ACCENT_COLOR})'
bash_indicator =      '─[\$](bold ${ACCENT_COLOR})'
zsh_indicator =        '─[λ](bold ${ACCENT_COLOR})'
unknown_indicator =    '─[?](bold ${ACCENT_COLOR})'
disabled = false
format = '$indicator'

[status]
disabled = false

